$(document).ready(function(){
	//append
	$("#target").append("<b>append</b>");
	//prepend
	$("#target").prepend("<b>prepend</b>");
	//insertBefore
	$("#target").before("<b>insertBefore</b>");
	//insertAfter
	$("#target").after("<b>insertAfter</b>");
});